### ISSUE TITLE
[FEATURE] Add query parameters to Contributions BB API spec and function arguments

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#616]
**Is your feature request related to a problem? Please describe.**
Currently, we are not listing which query parameters are available and how to use them. This needs to be added to API spec for it to appear in the API documentation as well as limiting which properties can be used for searching.

**Describe the solution you'd like**
For these GET endpoints, add query parameters to API spec and corresponding function arguments:
```
GET /contributions
GET /contributions/capabilities
GET /contributions/talents
```
Let's start with just the query parameter `name` for these endpoints which will filter data based on contribution, capability, and talent name respectively.

E.g. API spec description for a query parameter to search talents based on its name.

```
parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Talent name
```
References: 
https://swagger.io/docs/specification/describing-parameters/#query-parameters
https://connexion.readthedocs.io/en/latest/request.html#automatic-parameter-handling

**Describe alternatives you've considered**

**Additional context**
